from enum import StrEnum


class BookingEvent(StrEnum):
    CLARIFY_REQUESTED = "CLARIFY_REQUESTED"
    CLARIFY_LIMIT_REACHED = "CLARIFY_LIMIT_REACHED"

    BOOKING_CHANGE_CONFIRMED = "BOOKING_CHANGE_CONFIRMED"
    BOOKING_CHANGE_REJECTED = "BOOKING_CHANGE_REJECTED"
    BOOKING_LEFT_INITIAL = "BOOKING_LEFT_INITIAL"

    OPERATOR_REQUESTED = "OPERATOR_REQUESTED"
    OPERATOR_ESCALATED = "OPERATOR_ESCALATED"
